# http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-file-separation
---
hostname: all

# geerlingguy/ntp
ntp_timezone: America/New_York

# geerlingguy/firewall
firewall_allowed_tcp_ports:
  - "22"
  - "25"



# apolloclark/osquery
osquery:
  logger_path: "/var/log/osquery/"

# apolloclark/filebeat
filebeat:
 version: "5.x"
 install_only: "true"

# apolloclark/metricbeat
metricbeat:
 version: "5.x"
 install_only: "true"

# apolloclark/heartbeat
heartbeat:
 version: "5.x"
 install_only: "true"

# apolloclark/packetbeat
packetbeat:
  version: "5.x"
  install_only: "true"